# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2 
xcode_workspace: Example/MEVHorizontalContacts.xcworkspace #3
xcode_scheme: MEVHorizontalContacts-Example #4
xcode_sdk: iphonesimulator9.2 #5

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- pod lib lint
